# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-29T02:35:22+00:00

from __future__ import annotations

from enum import Enum
from typing import List, Optional

from pydantic import BaseModel, Field


class GoogleCloudPaymentsResellerSubscriptionV1Amount(BaseModel):
    amountMicros: Optional[str] = Field(
        None,
        description='Required. Amount in micros (1_000_000 micros = 1 currency unit)',
    )
    currencyCode: Optional[str] = Field(
        None,
        description='Required. Currency codes in accordance with [ISO-4217 Currency Codes] (https://en.wikipedia.org/wiki/ISO_4217). For example, USD.',
    )


class CancellationReason(Enum):
    CANCELLATION_REASON_UNSPECIFIED = 'CANCELLATION_REASON_UNSPECIFIED'
    CANCELLATION_REASON_FRAUD = 'CANCELLATION_REASON_FRAUD'
    CANCELLATION_REASON_REMORSE = 'CANCELLATION_REASON_REMORSE'
    CANCELLATION_REASON_ACCIDENTAL_PURCHASE = 'CANCELLATION_REASON_ACCIDENTAL_PURCHASE'
    CANCELLATION_REASON_PAST_DUE = 'CANCELLATION_REASON_PAST_DUE'
    CANCELLATION_REASON_ACCOUNT_CLOSED = 'CANCELLATION_REASON_ACCOUNT_CLOSED'
    CANCELLATION_REASON_UPGRADE_DOWNGRADE = 'CANCELLATION_REASON_UPGRADE_DOWNGRADE'
    CANCELLATION_REASON_USER_DELINQUENCY = 'CANCELLATION_REASON_USER_DELINQUENCY'
    CANCELLATION_REASON_SYSTEM_ERROR = 'CANCELLATION_REASON_SYSTEM_ERROR'
    CANCELLATION_REASON_OTHER = 'CANCELLATION_REASON_OTHER'


class GoogleCloudPaymentsResellerSubscriptionV1CancelSubscriptionRequest(BaseModel):
    cancelImmediately: Optional[bool] = Field(
        None,
        description='Optional. If true, Google will cancel the subscription immediately, and may or may not (based on the contract) issue a prorated refund for the remainder of the billing cycle. Otherwise, Google defers the cancelation at renewal_time, and will not issue a refund.',
    )
    cancellationReason: Optional[CancellationReason] = Field(
        None, description='Specifies the reason for the cancellation.'
    )


class Unit(Enum):
    UNIT_UNSPECIFIED = 'UNIT_UNSPECIFIED'
    MONTH = 'MONTH'
    DAY = 'DAY'


class GoogleCloudPaymentsResellerSubscriptionV1Duration(BaseModel):
    count: Optional[int] = Field(
        None, description='number of duration units to be included.'
    )
    unit: Optional[Unit] = Field(None, description='The unit used for the duration')


class GoogleCloudPaymentsResellerSubscriptionV1EntitleSubscriptionRequest(BaseModel):
    pass


class GoogleCloudPaymentsResellerSubscriptionV1ExtendSubscriptionResponse(BaseModel):
    cycleEndTime: Optional[str] = Field(
        None,
        description='The time at which the subscription is expected to be extended, in ISO 8061 format. UTC timezone. Example, "cycleEndTime":"2019-08-31T17:28:54.564Z"',
    )
    freeTrialEndTime: Optional[str] = Field(
        None,
        description='End of the free trial period, in ISO 8061 format. UTC timezone. Example, "freeTrialEndTime":"2019-08-31T17:28:54.564Z" This time will be set the same as initial subscription creation time if no free trial period is offered to the partner.',
    )
    renewalTime: Optional[str] = Field(
        None,
        description='Output only. The time at which the subscription is expected to be renewed by Google - a new charge will be incurred and the service entitlement will be renewed. A non-immediate cancellation will take place at this time too, before which, the service entitlement for the end user will remain valid. UTC timezone in ISO 8061 format. For example: "2019-08-31T17:28:54.564Z"',
    )


class GoogleCloudPaymentsResellerSubscriptionV1Extension(BaseModel):
    duration: Optional[GoogleCloudPaymentsResellerSubscriptionV1Duration] = Field(
        None,
        description='Specifies the period of access the subscription should grant.',
    )
    partnerUserToken: Optional[str] = Field(
        None, description='Required. Identifier of the end-user in partner’s system.'
    )


class GoogleCloudPaymentsResellerSubscriptionV1FindEligiblePromotionsRequest(BaseModel):
    filter: Optional[str] = Field(
        None,
        description='Optional. Specifies the filters for the promotion results. The syntax is defined in https://google.aip.dev/160 with the following caveats: - Only the following features are supported: - Logical operator `AND` - Comparison operator `=` (no wildcards `*`) - Traversal operator `.` - Has operator `:` (no wildcards `*`) - Only the following fields are supported: - `applicableProducts` - `regionCodes` - `youtubePayload.partnerEligibilityId` - `youtubePayload.postalCode` - Unless explicitly mentioned above, other features are not supported. Example: `applicableProducts:partners/partner1/products/product1 AND regionCodes:US AND youtubePayload.postalCode=94043 AND youtubePayload.partnerEligibilityId=eligibility-id`',
    )
    pageSize: Optional[int] = Field(
        None,
        description='Optional. The maximum number of promotions to return. The service may return fewer than this value. If unspecified, at most 50 products will be returned. The maximum value is 1000; values above 1000 will be coerced to 1000.',
    )
    pageToken: Optional[str] = Field(
        None,
        description='Optional. A page token, received from a previous `ListPromotions` call. Provide this to retrieve the subsequent page. When paginating, all other parameters provided to `ListPromotions` must match the call that provided the page token.',
    )


class Offering(Enum):
    OFFERING_UNSPECIFIED = 'OFFERING_UNSPECIFIED'
    OFFERING_VAS_BUNDLE = 'OFFERING_VAS_BUNDLE'
    OFFERING_VAS_STANDALONE = 'OFFERING_VAS_STANDALONE'
    OFFERING_HARD_BUNDLE = 'OFFERING_HARD_BUNDLE'
    OFFERING_SOFT_BUNDLE = 'OFFERING_SOFT_BUNDLE'


class SalesChannel(Enum):
    CHANNEL_UNSPECIFIED = 'CHANNEL_UNSPECIFIED'
    CHANNEL_RETAIL = 'CHANNEL_RETAIL'
    CHANNEL_ONLINE_WEB = 'CHANNEL_ONLINE_WEB'
    CHANNEL_ONLINE_ANDROID_APP = 'CHANNEL_ONLINE_ANDROID_APP'
    CHANNEL_ONLINE_IOS_APP = 'CHANNEL_ONLINE_IOS_APP'


class GoogleCloudPaymentsResellerSubscriptionV1GoogleOnePayload(BaseModel):
    campaigns: Optional[List[str]] = Field(
        None, description='Campaign attributed to sales of this subscription.'
    )
    offering: Optional[Offering] = Field(
        None,
        description='The type of offering the subscription was sold by the partner. e.g. VAS.',
    )
    salesChannel: Optional[SalesChannel] = Field(
        None,
        description='The type of sales channel through which the subscription was sold.',
    )
    storeId: Optional[str] = Field(
        None,
        description='The identifier for the partner store where the subscription was sold.',
    )


class GoogleCloudPaymentsResellerSubscriptionV1Location(BaseModel):
    postalCode: Optional[str] = Field(
        None, description='The postal code this location refers to. Ex. "94043"'
    )
    regionCode: Optional[str] = Field(
        None,
        description='2-letter ISO region code for current content region. Ex. “US” Please refers to: https://en.wikipedia.org/wiki/ISO_3166-1',
    )


class GoogleCloudPaymentsResellerSubscriptionV1ProductPriceConfig(BaseModel):
    amount: Optional[GoogleCloudPaymentsResellerSubscriptionV1Amount] = Field(
        None, description='Output only. The price in the region.'
    )
    regionCode: Optional[str] = Field(
        None,
        description='Output only. 2-letter ISO region code where the product is available in. Ex. "US".',
    )


class PromotionType(Enum):
    PROMOTION_TYPE_UNSPECIFIED = 'PROMOTION_TYPE_UNSPECIFIED'
    PROMOTION_TYPE_FREE_TRIAL = 'PROMOTION_TYPE_FREE_TRIAL'
    PROMOTION_TYPE_INTRODUCTORY_PRICING = 'PROMOTION_TYPE_INTRODUCTORY_PRICING'


class GoogleCloudPaymentsResellerSubscriptionV1PromotionIntroductoryPricingDetailsIntroductoryPricingSpec(
    BaseModel
):
    discountAmount: Optional[GoogleCloudPaymentsResellerSubscriptionV1Amount] = Field(
        None, description='Output only. The discount amount. The value is positive.'
    )
    discountRatioMicros: Optional[str] = Field(
        None,
        description='Output only. The discount percentage in micros. For example, 50,000 represents 5%.',
    )
    recurrenceCount: Optional[int] = Field(
        None,
        description='Output only. Output Only. The duration of an introductory offer in billing cycles.',
    )
    regionCode: Optional[str] = Field(
        None,
        description='Output only. 2-letter ISO region code where the product is available in. Ex. "US".',
    )


class GoogleCloudPaymentsResellerSubscriptionV1ServicePeriod(BaseModel):
    endTime: Optional[str] = Field(
        None,
        description='Optional. The end time of the service period. Time is exclusive.',
    )
    startTime: Optional[str] = Field(
        None,
        description='Required. The start time of the service period. Time is inclusive.',
    )


class ProcessingState(Enum):
    PROCESSING_STATE_UNSPECIFIED = 'PROCESSING_STATE_UNSPECIFIED'
    PROCESSING_STATE_CANCELLING = 'PROCESSING_STATE_CANCELLING'
    PROCESSING_STATE_RECURRING = 'PROCESSING_STATE_RECURRING'


class State(Enum):
    STATE_UNSPECIFIED = 'STATE_UNSPECIFIED'
    STATE_CREATED = 'STATE_CREATED'
    STATE_ACTIVE = 'STATE_ACTIVE'
    STATE_CANCELLED = 'STATE_CANCELLED'
    STATE_IN_GRACE_PERIOD = 'STATE_IN_GRACE_PERIOD'
    STATE_CANCEL_AT_END_OF_CYCLE = 'STATE_CANCEL_AT_END_OF_CYCLE'
    STATE_SUSPENDED = 'STATE_SUSPENDED'


class Reason(Enum):
    CANCELLATION_REASON_UNSPECIFIED = 'CANCELLATION_REASON_UNSPECIFIED'
    CANCELLATION_REASON_FRAUD = 'CANCELLATION_REASON_FRAUD'
    CANCELLATION_REASON_REMORSE = 'CANCELLATION_REASON_REMORSE'
    CANCELLATION_REASON_ACCIDENTAL_PURCHASE = 'CANCELLATION_REASON_ACCIDENTAL_PURCHASE'
    CANCELLATION_REASON_PAST_DUE = 'CANCELLATION_REASON_PAST_DUE'
    CANCELLATION_REASON_ACCOUNT_CLOSED = 'CANCELLATION_REASON_ACCOUNT_CLOSED'
    CANCELLATION_REASON_UPGRADE_DOWNGRADE = 'CANCELLATION_REASON_UPGRADE_DOWNGRADE'
    CANCELLATION_REASON_USER_DELINQUENCY = 'CANCELLATION_REASON_USER_DELINQUENCY'
    CANCELLATION_REASON_SYSTEM_ERROR = 'CANCELLATION_REASON_SYSTEM_ERROR'
    CANCELLATION_REASON_OTHER = 'CANCELLATION_REASON_OTHER'


class GoogleCloudPaymentsResellerSubscriptionV1SubscriptionCancellationDetails(
    BaseModel
):
    reason: Optional[Reason] = Field(
        None, description='The reason of the cancellation.'
    )


class RecurrenceType(Enum):
    LINE_ITEM_RECURRENCE_TYPE_UNSPECIFIED = 'LINE_ITEM_RECURRENCE_TYPE_UNSPECIFIED'
    LINE_ITEM_RECURRENCE_TYPE_PERIODIC = 'LINE_ITEM_RECURRENCE_TYPE_PERIODIC'
    LINE_ITEM_RECURRENCE_TYPE_ONE_TIME = 'LINE_ITEM_RECURRENCE_TYPE_ONE_TIME'


class State1(Enum):
    LINE_ITEM_STATE_UNSPECIFIED = 'LINE_ITEM_STATE_UNSPECIFIED'
    LINE_ITEM_STATE_ACTIVE = 'LINE_ITEM_STATE_ACTIVE'
    LINE_ITEM_STATE_INACTIVE = 'LINE_ITEM_STATE_INACTIVE'
    LINE_ITEM_STATE_NEW = 'LINE_ITEM_STATE_NEW'
    LINE_ITEM_STATE_ACTIVATING = 'LINE_ITEM_STATE_ACTIVATING'
    LINE_ITEM_STATE_DEACTIVATING = 'LINE_ITEM_STATE_DEACTIVATING'
    LINE_ITEM_STATE_WAITING_TO_DEACTIVATE = 'LINE_ITEM_STATE_WAITING_TO_DEACTIVATE'
    LINE_ITEM_STATE_OFF_CYCLE_CHARGING = 'LINE_ITEM_STATE_OFF_CYCLE_CHARGING'


class GoogleCloudPaymentsResellerSubscriptionV1SubscriptionLineItemOneTimeRecurrenceDetails(
    BaseModel
):
    servicePeriod: Optional[GoogleCloudPaymentsResellerSubscriptionV1ServicePeriod] = (
        Field(None, description='The service period of the ONE_TIME line item.')
    )


class Type(Enum):
    PROMOTION_TYPE_UNSPECIFIED = 'PROMOTION_TYPE_UNSPECIFIED'
    PROMOTION_TYPE_FREE_TRIAL = 'PROMOTION_TYPE_FREE_TRIAL'
    PROMOTION_TYPE_INTRODUCTORY_PRICING = 'PROMOTION_TYPE_INTRODUCTORY_PRICING'


class BillingCycleSpec(Enum):
    BILLING_CYCLE_SPEC_UNSPECIFIED = 'BILLING_CYCLE_SPEC_UNSPECIFIED'
    BILLING_CYCLE_SPEC_ALIGN_WITH_PREVIOUS_SUBSCRIPTION = (
        'BILLING_CYCLE_SPEC_ALIGN_WITH_PREVIOUS_SUBSCRIPTION'
    )
    BILLING_CYCLE_SPEC_START_IMMEDIATELY = 'BILLING_CYCLE_SPEC_START_IMMEDIATELY'


class GoogleCloudPaymentsResellerSubscriptionV1SubscriptionUpgradeDowngradeDetails(
    BaseModel
):
    billingCycleSpec: Optional[BillingCycleSpec] = Field(
        None,
        description='Required. Specifies the billing cycle spec for the new upgraded/downgraded subscription.',
    )
    previousSubscriptionId: Optional[str] = Field(
        None,
        description='Required. The previous subscription id to be replaced. This is not the full resource name, use the subscription_id segment only.',
    )


class GoogleCloudPaymentsResellerSubscriptionV1UndoCancelSubscriptionRequest(BaseModel):
    pass


class GoogleCloudPaymentsResellerSubscriptionV1YoutubePayload(BaseModel):
    partnerEligibilityIds: Optional[List[str]] = Field(
        None,
        description='The list of eligibility_ids which are applicable for the line item.',
    )


class GoogleTypeLocalizedText(BaseModel):
    languageCode: Optional[str] = Field(
        None,
        description='The text\'s BCP-47 language code, such as "en-US" or "sr-Latn". For more information, see http://www.unicode.org/reports/tr35/#Unicode_locale_identifier.',
    )
    text: Optional[str] = Field(
        None,
        description="Localized string in the language corresponding to `language_code' below.",
    )


class FieldXgafv(Enum):
    field_1 = '1'
    field_2 = '2'


class Alt(Enum):
    json = 'json'
    media = 'media'
    proto = 'proto'


class GoogleCloudPaymentsResellerSubscriptionV1ExtendSubscriptionRequest(BaseModel):
    extension: Optional[GoogleCloudPaymentsResellerSubscriptionV1Extension] = Field(
        None,
        description='Required. Specifies details of the extension. Currently, the duration of the extension must be exactly one billing cycle of the original subscription.',
    )
    requestId: Optional[str] = Field(
        None,
        description='Required. Restricted to 36 ASCII characters. A random UUID is recommended. The idempotency key for the request. The ID generation logic is controlled by the partner. request_id should be the same as on retries of the same request. A different request_id must be used for a extension of a different cycle. A random UUID is recommended.',
    )


class GoogleCloudPaymentsResellerSubscriptionV1Product(BaseModel):
    name: Optional[str] = Field(
        None,
        description='Output only. Response only. Resource name of the product. It will have the format of "partners/{partner_id}/products/{product_id}"',
    )
    priceConfigs: Optional[
        List[GoogleCloudPaymentsResellerSubscriptionV1ProductPriceConfig]
    ] = Field(
        None,
        description='Output only. Price configs for the product in the available regions.',
    )
    regionCodes: Optional[List[str]] = Field(
        None,
        description='Output only. 2-letter ISO region code where the product is available in. Ex. "US" Please refers to: https://en.wikipedia.org/wiki/ISO_3166-1',
    )
    subscriptionBillingCycleDuration: Optional[
        GoogleCloudPaymentsResellerSubscriptionV1Duration
    ] = Field(
        None,
        description='Output only. Specifies the length of the billing cycle of the subscription.',
    )
    titles: Optional[List[GoogleTypeLocalizedText]] = Field(
        None, description='Output only. Localized human readable name of the product.'
    )


class GoogleCloudPaymentsResellerSubscriptionV1ProductPayload(BaseModel):
    googleOnePayload: Optional[
        GoogleCloudPaymentsResellerSubscriptionV1GoogleOnePayload
    ] = Field(None, description='Payload specific to Google One products.')
    youtubePayload: Optional[
        GoogleCloudPaymentsResellerSubscriptionV1YoutubePayload
    ] = Field(None, description='Payload specific to Youtube products.')


class GoogleCloudPaymentsResellerSubscriptionV1PromotionIntroductoryPricingDetails(
    BaseModel
):
    introductoryPricingSpecs: Optional[
        List[
            GoogleCloudPaymentsResellerSubscriptionV1PromotionIntroductoryPricingDetailsIntroductoryPricingSpec
        ]
    ] = Field(None, description='Specifies the introductory pricing periods.')


class GoogleCloudPaymentsResellerSubscriptionV1SubscriptionPromotionSpec(BaseModel):
    freeTrialDuration: Optional[GoogleCloudPaymentsResellerSubscriptionV1Duration] = (
        Field(
            None,
            description='Output only. The duration of the free trial if the promotion is of type FREE_TRIAL.',
        )
    )
    introductoryPricingDetails: Optional[
        GoogleCloudPaymentsResellerSubscriptionV1PromotionIntroductoryPricingDetails
    ] = Field(
        None,
        description='Output only. The details of the introductory pricing spec if the promotion is of type INTRODUCTORY_PRICING.',
    )
    promotion: Optional[str] = Field(
        None,
        description="Required. Promotion resource name that identifies a promotion. The format is 'partners/{partner_id}/promotions/{promotion_id}'.",
    )
    type: Optional[Type] = Field(
        None, description='Output only. The type of the promotion for the spec.'
    )


class GoogleCloudPaymentsResellerSubscriptionV1ListProductsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is empty, there are no subsequent pages.',
    )
    products: Optional[List[GoogleCloudPaymentsResellerSubscriptionV1Product]] = Field(
        None, description='The products for the specified partner.'
    )


class GoogleCloudPaymentsResellerSubscriptionV1Promotion(BaseModel):
    applicableProducts: Optional[List[str]] = Field(
        None,
        description='Output only. The product ids this promotion can be applied to.',
    )
    endTime: Optional[str] = Field(
        None,
        description='Optional. Specifies the end time (exclusive) of the period that the promotion is available in. If unset, the promotion is available indefinitely.',
    )
    freeTrialDuration: Optional[GoogleCloudPaymentsResellerSubscriptionV1Duration] = (
        Field(
            None,
            description='Optional. Specifies the duration of the free trial of the subscription when promotion_type is PROMOTION_TYPE_FREE_TRIAL',
        )
    )
    introductoryPricingDetails: Optional[
        GoogleCloudPaymentsResellerSubscriptionV1PromotionIntroductoryPricingDetails
    ] = Field(
        None,
        description='Optional. Specifies the introductory pricing details when the promotion_type is PROMOTION_TYPE_INTRODUCTORY_PRICING.',
    )
    name: Optional[str] = Field(
        None,
        description='Output only. Response only. Resource name of the subscription promotion. It will have the format of "partners/{partner_id}/promotion/{promotion_id}"',
    )
    promotionType: Optional[PromotionType] = Field(
        None,
        description='Output only. Output Only. Specifies the type of the promotion.',
    )
    regionCodes: Optional[List[str]] = Field(
        None,
        description='Output only. 2-letter ISO region code where the promotion is available in. Ex. "US" Please refers to: https://en.wikipedia.org/wiki/ISO_3166-1',
    )
    startTime: Optional[str] = Field(
        None,
        description='Optional. Specifies the start time (inclusive) of the period that the promotion is available in.',
    )
    titles: Optional[List[GoogleTypeLocalizedText]] = Field(
        None, description='Output only. Localized human readable name of the promotion.'
    )


class GoogleCloudPaymentsResellerSubscriptionV1SubscriptionLineItem(BaseModel):
    amount: Optional[GoogleCloudPaymentsResellerSubscriptionV1Amount] = Field(
        None,
        description='Output only. The price of the product/service in this line item. The amount could be the wholesale price, or it can include a cost of sale based on the contract.',
    )
    description: Optional[str] = Field(
        None, description='Output only. Description of this line item.'
    )
    lineItemFreeTrialEndTime: Optional[str] = Field(
        None,
        description='Output only. The free trial end time will be populated after the line item is successfully processed. End time of the line item free trial period, in ISO 8061 format. For example, "2019-08-31T17:28:54.564Z". It will be set the same as createTime if no free trial promotion is specified.',
    )
    lineItemPromotionSpecs: Optional[
        List[GoogleCloudPaymentsResellerSubscriptionV1SubscriptionPromotionSpec]
    ] = Field(
        None,
        description='Optional. The promotions applied on the line item. It can be: - a free trial promotion, which overrides the subscription-level free trial promotion. - an introductory pricing promotion. When used as input in Create or Provision API, specify its resource name only.',
    )
    oneTimeRecurrenceDetails: Optional[
        GoogleCloudPaymentsResellerSubscriptionV1SubscriptionLineItemOneTimeRecurrenceDetails
    ] = Field(
        None,
        description='Output only. Details only set for a ONE_TIME recurrence line item.',
    )
    product: Optional[str] = Field(
        None,
        description="Required. Product resource name that identifies one the line item The format is 'partners/{partner_id}/products/{product_id}'.",
    )
    productPayload: Optional[
        GoogleCloudPaymentsResellerSubscriptionV1ProductPayload
    ] = Field(
        None, description='Optional. Product specific payload for this line item.'
    )
    recurrenceType: Optional[RecurrenceType] = Field(
        None, description='Output only. The recurrence type of the line item.'
    )
    state: Optional[State1] = Field(
        None, description='Output only. The state of the line item.'
    )


class GoogleCloudPaymentsResellerSubscriptionV1FindEligiblePromotionsResponse(
    BaseModel
):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is empty, there are no subsequent pages.',
    )
    promotions: Optional[List[GoogleCloudPaymentsResellerSubscriptionV1Promotion]] = (
        Field(None, description='The promotions for the current user.')
    )


class GoogleCloudPaymentsResellerSubscriptionV1ListPromotionsResponse(BaseModel):
    nextPageToken: Optional[str] = Field(
        None,
        description='A token, which can be sent as `page_token` to retrieve the next page. If this field is empty, there are no subsequent pages.',
    )
    promotions: Optional[List[GoogleCloudPaymentsResellerSubscriptionV1Promotion]] = (
        Field(None, description='The promotions for the specified partner.')
    )


class GoogleCloudPaymentsResellerSubscriptionV1Subscription(BaseModel):
    cancellationDetails: Optional[
        GoogleCloudPaymentsResellerSubscriptionV1SubscriptionCancellationDetails
    ] = Field(
        None,
        description='Output only. Describes the details of a cancelled subscription. Only applicable to subscription of state `STATE_CANCELLED`.',
    )
    createTime: Optional[str] = Field(
        None,
        description='Output only. System generated timestamp when the subscription is created. UTC timezone.',
    )
    cycleEndTime: Optional[str] = Field(
        None,
        description='Output only. The time at which the subscription is expected to be extended, in ISO 8061 format. UTC timezone. For example: "2019-08-31T17:28:54.564Z"',
    )
    endUserEntitled: Optional[bool] = Field(
        None,
        description='Output only. Indicates if the subscription is entitled to the end user.',
    )
    freeTrialEndTime: Optional[str] = Field(
        None,
        description='Output only. End of the free trial period, in ISO 8061 format. For example, "2019-08-31T17:28:54.564Z". It will be set the same as createTime if no free trial promotion is specified.',
    )
    lineItems: Optional[
        List[GoogleCloudPaymentsResellerSubscriptionV1SubscriptionLineItem]
    ] = Field(None, description='Required. The line items of the subscription.')
    name: Optional[str] = Field(
        None,
        description='Optional. Resource name of the subscription. It will have the format of "partners/{partner_id}/subscriptions/{subscription_id}". This is available for authorizeAddon, but otherwise is response only.',
    )
    partnerUserToken: Optional[str] = Field(
        None,
        description='Required. Identifier of the end-user in partner’s system. The value is restricted to 63 ASCII characters at the maximum.',
    )
    processingState: Optional[ProcessingState] = Field(
        None,
        description='Output only. Describes the processing state of the subscription. See more details at [the lifecycle of a subscription](/payments/reseller/subscription/reference/index/Receive.Notifications#payments-subscription-lifecycle).',
    )
    products: Optional[List[str]] = Field(
        None,
        description="Required. Deprecated: consider using `line_items` as the input. Required. Resource name that identifies the purchased products. The format will be 'partners/{partner_id}/products/{product_id}'.",
    )
    promotionSpecs: Optional[
        List[GoogleCloudPaymentsResellerSubscriptionV1SubscriptionPromotionSpec]
    ] = Field(
        None,
        description='Optional. Subscription-level promotions. Only free trial is supported on this level. It determines the first renewal time of the subscription to be the end of the free trial period. Specify the promotion resource name only when used as input.',
    )
    promotions: Optional[List[str]] = Field(
        None,
        description="Optional. Deprecated: consider using the top-level `promotion_specs` as the input. Optional. Resource name that identifies one or more promotions that can be applied on the product. A typical promotion for a subscription is Free trial. The format will be 'partners/{partner_id}/promotions/{promotion_id}'.",
    )
    redirectUri: Optional[str] = Field(
        None,
        description='Output only. The place where partners should redirect the end-user to after creation. This field might also be populated when creation failed. However, Partners should always prepare a default URL to redirect the user in case this field is empty.',
    )
    renewalTime: Optional[str] = Field(
        None,
        description='Output only. The time at which the subscription is expected to be renewed by Google - a new charge will be incurred and the service entitlement will be renewed. A non-immediate cancellation will take place at this time too, before which, the service entitlement for the end user will remain valid. UTC timezone in ISO 8061 format. For example: "2019-08-31T17:28:54.564Z"',
    )
    serviceLocation: Optional[GoogleCloudPaymentsResellerSubscriptionV1Location] = (
        Field(
            None,
            description='Required. The location that the service is provided as indicated by the partner.',
        )
    )
    state: Optional[State] = Field(
        None,
        description='Output only. Describes the state of the subscription. See more details at [the lifecycle of a subscription](/payments/reseller/subscription/reference/index/Receive.Notifications#payments-subscription-lifecycle).',
    )
    updateTime: Optional[str] = Field(
        None,
        description='Output only. System generated timestamp when the subscription is most recently updated. UTC timezone.',
    )
    upgradeDowngradeDetails: Optional[
        GoogleCloudPaymentsResellerSubscriptionV1SubscriptionUpgradeDowngradeDetails
    ] = Field(
        None,
        description='Optional. Details about the previous subscription that this new subscription upgrades/downgrades from. Only populated if this subscription is an upgrade/downgrade from another subscription.',
    )


class GoogleCloudPaymentsResellerSubscriptionV1UndoCancelSubscriptionResponse(
    BaseModel
):
    subscription: Optional[GoogleCloudPaymentsResellerSubscriptionV1Subscription] = (
        Field(None, description='The updated subscription resource.')
    )


class GoogleCloudPaymentsResellerSubscriptionV1CancelSubscriptionResponse(BaseModel):
    subscription: Optional[GoogleCloudPaymentsResellerSubscriptionV1Subscription] = (
        Field(None, description='The cancelled subscription resource.')
    )


class GoogleCloudPaymentsResellerSubscriptionV1EntitleSubscriptionResponse(BaseModel):
    subscription: Optional[GoogleCloudPaymentsResellerSubscriptionV1Subscription] = (
        Field(None, description='The subscription that has user linked to it.')
    )
